export const QUERY_KEY_GROUPACTION = `group_action`;
export const QUERY_KEY_BOOKMARK = `bookmark`;
export const QUERY_KEY_USER = `user`;
export const QUERY_KEY_COMMUNITYLIST = `communityList`;
export const QUERY_KEY_GOODS = `goods`;
export const QUERY_KEY_INDIVIDUALACTION = `individual_action`;
export const QUERY_KEY_LIKES = `likes`;
export const QUERY_KEY_MY_INDIVIDUALACTION = `my_individual_actions`; // queryFn은 다른데 key 통일할수있을지?
export const QUERY_KEY_MY_COMMUNITYPOST = `my_community_posts`;
export const QUERY_KEY_MY_BOOKMARK = `my_bookmarked_actions`;
export const QUERY_KEY_COMMUNITY_POST = `communityPost`;
export const QEURY_KEY_COMMUNITY_COMMENTS_LIST = `communityCommentsList`;
export const QUERY_KEY_USER_INFO = `public_user_info`;
export const QUERY_KEY_GREEN_ACTION_IMAGE = `green_action_images`;
export const QUERY_KEY_COMMUNITY_POSTS_LIKES = `community_posts_likes`;
export const QUERY_KEY_INDIV_ACTIONS_BOOKMARKS = `individual_actions_bookmarks`;
export const QUERY_KEY_INDIVIDUALACTION_FOR_EDIT = `individual_action_for_edit`;
export const QUERY_KEY_INDIVIDUALACTION_IMAGE_FILES = `individual_action_image_files`;
